# Generated by Django 3.2.5 on 2021-07-08 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='MyNetwork', max_length=255),
        ),
    ]
